---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  #  - name: centos-6.4

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    run_list:
      # - ["recipe[eol-cookbook::default]","recipe[eol-cookbook::database]","recipe[eol-cookbook::memcached]","recipe[eol-cookbook::redis]","recipe[eol-cookbook::app]"]
      - ["recipe[eol-cookbook::default]","recipe[eol-cookbook::app]"]
    attributes:
      mysql:
        server_debian_password: "test"
        server_root_password: "test"
        server_repl_password: "test"
