---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  #  - name: centos-6.4

suites:
  - name: default
    run_list:
      - ["recipe[eol-cookbook::default]","recipe[eol-cookbook::database]","recipe[eol-cookbook::memcached]","recipe[eol-cookbook::redis]"]
    attributes:
      mysql:
        server_debian_password: "test"
        server_root_password: "test"
        server_repl_password: "test"
